spring.application.name=ayoubunsourirepourtous
# H2 en fichier (persistant)
spring.datasource.url=jdbc:h2:file:./data/ayoubunsourirepourtous
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.thymeleaf.cache=false

# upload
# Taille max d'un fichier
spring.servlet.multipart.max-file-size=10MB

# Taille max de la requête (tous les fichiers + champs)
spring.servlet.multipart.max-request-size=30MB




spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
# dossier où stocker les images
app.upload-dir=src/main/resources/static/uploads

app.admin.username=admin
app.admin.password=Ayoub2024!
